# Check out https://hub.docker.com/_/node to select a new base image
FROM node:14.16.0-alpine
WORKDIR /app
COPY ./package.json .
COPY tsconfig* ./
COPY ormconfig* ./
COPY src ./src
COPY .env* ./
RUN yarn
EXPOSE 3000
CMD [ "yarn", "dev" ]
